use_frameworks!

platform :ios, '10.0'

target 'LLNetworkAccessibility-Swift_Example' do
  pod 'LLNetworkAccessibility-Swift', :path => '../'

  target 'LLNetworkAccessibility-Swift_Tests' do
    inherit! :search_paths

    
  end
end
